# Generated by Django 2.0.5 on 2018-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
                ('oid', models.IntegerField()),
                ('primary_loc', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('match_addr', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=20)),
                ('ref_id', models.IntegerField()),
                ('geographic_location', models.CharField(max_length=100)),
            ],
        ),
    ]
