# Generated by Django 2.0.5 on 2018-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
