# Generated by Django 2.0.5 on 2018-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('data', '0003_auto_20180601_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='lid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='oid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
