# Generated by Django 2.0.5 on 2018-06-06 17:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('data', '0005_auto_20180606_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lid',
            new_name='cid',
        ),
    ]
