# Generated by Django 2.0.5 on 2018-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('data', '0006_auto_20180606_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='contact',
            name='cid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
