# Generated by Django 2.0.5 on 2018-06-06 18:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('data', '0007_auto_20180606_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Data',
        ),
    ]
