# Generated by Django 2.0.5 on 2018-06-06 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0008_auto_20180606_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Location',
        ),
    ]
    atomic = False
