# Generated by Django 2.0.5 on 2018-06-06 19:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180606_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('year_founded', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ally', models.BooleanField(default=False)),
                ('defunct', models.BooleanField(default=False)),
                ('hide_from_site', models.BooleanField(default=False)),
                ('icon_group_id', models.IntegerField(blank=True, null=True)),
                ('oid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Location')),
            ],
        ),
    ]
