# Generated by Django 2.0.5 on 2018-07-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20180615_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUnions',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Credit Unions',
                'proxy': True,
                'indexes': [],
            },
            bases=('data.locations',),
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'managed': False, 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'managed': False, 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='organizations',
            options={'managed': False, 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'managed': False, 'verbose_name_plural': 'Types'},
        ),
    ]
