# Generated by Django 2.0.5 on 2018-07-26 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20180716_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NCUA_edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(blank=True, max_length=150, null=True)),
                ('oid', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_loc', models.NullBooleanField()),
                ('location_name', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=150, null=True)),
                ('county', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('match_addr', models.CharField(blank=True, max_length=150, null=True)),
                ('side', models.CharField(blank=True, max_length=150, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=150, null=True)),
                ('geographic_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='creditunions',
            options={'verbose_name_plural': 'Locations (credit unions)'},
        ),
        migrations.AlterModelOptions(
            name='icongroups',
            options={'managed': False, 'verbose_name_plural': 'Icon groups'},
        ),
        migrations.AlterModelOptions(
            name='naicsindustries',
            options={'managed': False, 'verbose_name_plural': 'Naics industries'},
        ),
        migrations.AlterModelOptions(
            name='naicssectors',
            options={'managed': False, 'verbose_name_plural': 'Naics sectors'},
        ),
    ]
