# Generated by Django 2.0.5 on 2018-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20180726_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncua_edit',
            options={'verbose_name_plural': 'NCUA (edit)'},
        ),
        migrations.AlterField(
            model_name='ncua',
            name='oid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
